[package]
name = "dv_os"
version = "0.0.1"
authors = ["Divy Jain <dkj@somaiya.edu>"]
edition = "2018"

[dependencies]
rlibc = "1.0.0"
bootloader = "0.9.8"
volatile = "0.3.0"
spin = "0.5.2"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
